--COMMENT TABLE FIELD

--SELECT COMMENT IS MUST KNOW POST AND ID
SELECT USER_VIEW.ID,COMMENT.COMMENT_DATE,COMMENT.CONTEXT FROM COMMENT 
INNER JOIN USER_VIEW 
ON USER_VIEW.ID_NUM = COMMENT.ID_NUM 
INNER JOIN POST 
ON POST.POST_NUM = COMMENT.POST_NUM;

/* 
INSERT COMMENT IS MUST AJAX COMUNICATION
AND KNOW USER ID_NUM AND POST_NUM
*/
INSERT INTO COMMENT (ID_NUM,POST_NUM,CONTEXT)
VALUES ('ID_NUM','POST_NUM','CONTEXT');

/*
DELETE COMMENT IS MUST CONTROLLER SEND REFLASH
AND HAVE TO GET PASSWORD BECAUSE USER CHECK
*/
DELETE FROM COMMENT
WHERE COMMENT_NUM = 'NUM' 
AND ID_NUM = (
	SELECT ID_NUM FROM USER_INFORMATION
	WHERE COMMENT.ID_NUM = 'ID_NUM'
	AND USER_INFORMATION.
-- ID_PW CHECKING

