--MENU TABLE FIELD
--MENU_NUM , MENU_NAME

SELECT * FROM MENU;
SELECT * FROM MENU WHERE MENU_NAME ='NAME';

-- SELECT COUNTING POST
SELECT MENU.MENU_NAME,COUNT(*) FROM MENU 
INNER JOIN POST 
ON MENU.MENU_NUM = POST.MENU_NUM 
GROUP BY MENU.MENU_NAME;



