POST TABLE FILED
POST_NUM
ID_NUM
MENU_NUM
POST_NAME
POST_DATE
// YOU CAN CHAGNE POST_NAME , MENU_NUM

POST QUERY

SELECT POST_NUM,POST_NAME,POST_DATE FROM POST;

SELECT POST_NUM,POST_NAME,POST_DATE FROM POST;
WHERE ID_NUM = ID_NUM;

SELECT POST_NUM,POST_NAME,POST_DATE FROM POST;
WHERE MENU_NUM= MENU_NUM;

SELECT POST_NUM,POST_NAME,POST_DATE FROM POST;
WHERE POST_NAME = 'NAME'; // SEARCH DATA OF NAME

SELECT POST_NUM,POST_NAME,POST_DATE FROM POST;
WHERE POST_DATE < 'M_DATE'; // SEARCH DATA OF DATE


//IF DON`T KNOW MENU_NAME OR ID_NAME
SELECT POST_NUM,POST_NAME,POST_DATE FROM POST
WHERE ID_NUM = 
(
	SELECT ID_NUM FROM USER_INFORMATION
	WHERE ID = 'ID'
)

SELECT * FROM POST
WHERE MENU_NUM = 
(
	SELECT MENU_NUM FROM MENU
	WHERE MENU_NAME = 'NAME'
)

//INSERT POST QUERY
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES ('ID_NUM','MENU_NUM','POST_NUM')
//UPDATE POST QUERY
UPDATE POST
SET 
POST_NAME = 'NAME',
MENU_NUM = M_MENU_NUM,

//DELETE POST QUERY
DELETE POST
WHERE POST_NUM = POST_NUM;

DELETE POST
WHERE POST_NAME = 'NAME';
