--POST TABLE FILED
--POST_NUM,ID_NUM,MENU_NUM,POST_NAME,POST_DATE
--YOU CAN CHAGNE POST_NAME , MENU_NUM
--POST QUERY(POST LIST SELECTION)
SELECT POST_NUM,POST_NAME,POST_DATE,THUMBNAIL FROM POST;
--ID SEARCH POST
SELECT POST_NUM,POST_NAME,POST_DATE,THUMBNAIL FROM POST;
WHERE ID_NUM = ID_NUM;
--MENU SEARCH POST
SELECT POST_NUM,POST_NAME,POST_DATE,THUMBNAIL FROM POST;
WHERE MENU_NUM= MENU_NUM;
--POST NAME SEARCH
SELECT POST_NUM,POST_NAME,POST_DATE,THUMBNAIL FROM POST;
WHERE POST_NAME = 'NAME'; // SEARCH DATA OF NAME
--DATE RANGTH SEARCH
SELECT POST_NUM,POST_NAME,POST_DATE,THUMBNAIL FROM POST;
WHERE POST_DATE > 'M_DATE'; // SEARCH DATA OF DATE

--POST CONTENT QUERY
SELECT POST_NUM,POST_NAME,POST_DATE,POST_CONTENTS FROM POST;

--IF DON`T KNOW MENU_NUM OR ID_NUM
--SEARCHING ID_NAME
SELECT POST_NUM,POST_NAME,POST_DATE,THUMBNAIL FROM POST
INNER JOIN USER_VIEW
ON POST.ID_NUM = USER_VIEW.ID_NUM
WHERE USER_VIEW.ID = 'ID';
--SEARCHING MENU_NAME
SELECT POST_NUM,POST_NAME,POST_DATE,THUMBNAIL FROM POST
INNER JOIN MENU
ON POST.MENU_NUM = MENU.MENU_NUM
WHERE MENU_NAME = 'NAME';

--INSERT POST QUERY
--DEFAULT INSERT
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME,POST_CONTENTS)
VALUES ('ID_NUM','MENU_NUM','POST_NUM','POST_CONTENTS');

--THUMBNAIL INSERT
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME,POST_CONTENTS,THUMBNAIL)
VALUES ('ID_NUM','MENU_NUM','POST_NUM','POST_CONTENTS','LOCATION');
--UPDATE POST QUERY
UPDATE POST
SET 
POST_NAME = 'NAME',
MENU_NUM = M_MENU_NUM, ...

--DELETE POST QUERY
DELETE POST
WHERE POST_NUM = POST_NUM;
--DELETE POST NAME QUERY
DELETE POST
WHERE POST_NAME = 'NAME';
