--USER TEST SOURCE
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST1','1234','SONG');
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST2','1234','SONGE');
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST3','1234','SONG');
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST4','1234','SONG');
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST5','1234','SONG');
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST6','1234','SONG');
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST7','1234','SONG');
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST8','1234','SONG');
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST9','1234','SONG');
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST10','1234','SONG');
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST11','1234','SONG');
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST12','1234','SONG');
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('TEST13','1234','SONG');

--MENU TEST SOURCE
INSERT INTO MENU(MENU_NAME)
VALUES('C');

INSERT INTO MENU(MENU_NAME)
VALUES('JAVA');

INSERT INTO MENU(MENU_NAME)
VALUES('EMBEDDED');

INSERT INTO MENU(MENU_NAME)
VALUES('HTML/CSS');

INSERT INTO MENU(MENU_NAME)
VALUES('JAVASCRIPT');

INSERT INTO MENU(MENU_NAME)
VALUES('JQUERY,AJAX');

INSERT INTO MENU(MENU_NAME)
VALUES('SPRING');

INSERT INTO MENU(MENU_NAME)
VALUES('DATABASE(MYSQL)');

INSERT INTO MENU(MENU_NAME)
VALUES('DATABASE(ORACLE)');

--POST INSERT QUERY
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(1,1,'TEST1');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(1,1,'TEST2');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(1,1,'TEST3');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(1,1,'TEST4');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(1,1,'TEST5');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(1,1,'TEST6');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(1,1,'TEST7');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(1,1,'TEST8');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(1,1,'TEST9');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(2,2,'TEST1 by 2');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(2,2,'TEST2 by 2');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(2,1,'TEST1 by 2');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(2,1,'TEST2 by 2');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(2,3,'TEST1 by 2');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(2,3,'TEST2 by 2');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(2,3,'TEST1 by 2');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(2,3,'TEST2 by 2');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(2,3,'TEST1 by 2');
INSERT INTO POST(ID_NUM,MENU_NUM,POST_NAME)
VALUES(2,3,'TEST2 by 2');

--COMMENT INSERT QUERY
INSERT INTO COMMENT(ID_NUM,POST_NUM,CONTEXT)
VALUES(1,1,"하아");
INSERT INTO COMMENT(ID_NUM,POST_NUM,CONTEXT)
VALUES(2,1,"하아");
INSERT INTO COMMENT(ID_NUM,POST_NUM,CONTEXT)
VALUES(3,1,"하아");
INSERT INTO COMMENT(ID_NUM,POST_NUM,CONTEXT)
VALUES(4,1,"하아");
INSERT INTO COMMENT(ID_NUM,POST_NUM,CONTEXT) 
VALUES(5,2,"TEST COMMENT");
INSERT INTO COMMENT(ID_NUM,POST_NUM,CONTEXT) 
VALUES(3,10,"TEST_COMMENT BY 10");

