USER_INFORMATION TABLE FIELD
ID_NUM
ID,PW,NAME,PHONE_NUMBER,ADDRESS,SIGN_DATE,SELF_INSTRUCTION

YOU CAN CHANGE
PW,NAME,PHONE_NUMBER,ADDRESS,SELF_INSTRUCTION

SELECT * FROM USER_INFORMATION; // ALL USER
SELECT * FROM USER_INFORMATION
WHERE ID = 'ID';  //SEARCH ID



INSERT INTO USER_INFORMATION(ID,PW,NAME)  // DEFAULT SETTING
VALUES('ID','PW','NAME')

INSERT INTO USER_INFO(ID,PW,NAME ... )
VALUES('ID','PW','NAME',...)

UPDATE USER_INFORMATION
SET PW = 'PW' 
,
NAME = 'NAME'
,
PHONE_NUMBER = 'PHONE_NUMBER',
...
WHERE ID = 'ID'

DELETE FROM USER_INFORMATION
WHERE ID = 'ID'
