--USER_INFORMATION TABLE FIELD
--ID_NUM
--ID,PW,NAME,PHONE_NUMBER,ADDRESS,SIGN_DATE,SELF_INSTRUCTION
--YOU CAN CHANGE
--PW,NAME,PHONE_NUMBER,ADDRESS,SELF_INSTRUCTION

--ALL USER SELECT
SELECT * FROM USER_VIEW;


--LOGIN SELECT 
SELECT * FROM USER_INFORMATION
WHERE ID = 'ID' AND PW='PW';

--USER SELECT
SELECT * FROM USER_VIEW;
WHERE ID = 'ID';

--INSERT USER DEFAULT SETTING
INSERT INTO USER_INFORMATION(ID,PW,NAME)
VALUES('ID','PW','NAME')

--INSERT USER ETC
INSERT INTO USER_INFO(ID,PW,NAME ... )
VALUES('ID','PW','NAME',...)

--UPDATE USER
UPDATE USER_INFORMATION
SET PW = 'PW' ,
NAME = 'NAME',
PHONE_NUMBER = 'PHONE_NUMBER',
...
WHERE ID = 'ID'

--DELETE USER MUST HAVING ID AND PASSWORD
DELETE FROM USER_INFORMATION
WHERE ID = 'ID'
AND PW = 'PW';
